services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    network_mode: host
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
      - SUBDOMAINS=
      - TOKEN=
    volumes:
      - ~/.duckdns/config:/config
    restart: unless-stopped
