services:
  prometheus:
    image: prom/prometheus:latest
    hostname: '{{.Node.Hostname}}'
    networks:
      - traefik-public
    ports:
      - "9090:9090"
    volumes:
      - prometheus_storage:/prometheus 
    configs:
      - source:  prometheus-config
        target: /etc/prometheus/prometheus.yml
        mode: 0444
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.prometheus.rule=Host(`prometheus.home.eduardocouto.dev`)"
        - "traefik.http.routers.prometheus.entrypoints=https"
        - "traefik.http.routers.prometheus.tls=true"
        - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      placement:
        constraints:
          - node.hostname == rpi5-1

configs:
  prometheus-config:
    file: ./prometheus.yml

volumes:
  prometheus_storage:

networks:
  traefik-public:
    external: true
    driver: overlay
    attachable: true