global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s    # Consuming a lot of resources at 15s

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8082']

  - job_name: 'speedtest'
    static_configs:
      - targets: ['speedtest-exporter:9798']
    scrape_interval: 60m
    scrape_timeout: 90s # It takes time to execute

  - job_name: 'P110-exporter'
    static_configs:
      - targets: ['P110-exporter:9333']