services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    hostname: '{{.Node.Hostname}}'
    networks: 
      - traefik-public
    privileged: true
    ports:
      - "9180:8080"
    volumes:
      - /var/run:/var/run:rw
      - /sys:/sys:rw               
      - /var/lib/docker/:/var/lib/docker:ro
      - /proc:/proc        
      - /cgroup:/cgroup:ro
    command:
      - '--docker_only=true'
      - '--housekeeping_interval=30s'
      - '--max_housekeeping_interval=60s'
      - '--store_container_labels=false'
      - '--disable_metrics=percpu,sched,hugetlb'
    deploy:
      placement:
        constraints:
          - node.hostname == rpi5-1

networks:
  traefik-public:
    external: true
    driver: overlay
    attachable: true