services:
  ezbookkeeping:
    image: mayswind/ezbookkeeping
    hostname: '{{.Node.Hostname}}'
    networks:
      - traefik-public
    volumes:
      - ezbookkeeping-data:/ezbookkeeping/data
      - ezbookkeeping-storage:/ezbookkeeping/storage
    environment:
      EBK_SERVER_DOMAIN: "ezbookkeeping.home.eduardocouto.dev"
    deploy:
      placement:
        constraints:
          - node.hostname == rpi5-1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.ezbookkeeping.rule=Host(`ezbookkeeping.home.eduardocouto.dev`)"
        - "traefik.http.routers.ezbookkeeping.entrypoints=https"
        - "traefik.http.routers.ezbookkeeping.tls=true"
        - "traefik.http.services.ezbookkeeping.loadbalancer.server.port=8080"
        - "traefik.http.services.ezbookkeeping.loadbalancer.passHostHeader=true"
      replicas: 1

volumes:
  ezbookkeeping-data:
  ezbookkeeping-storage:

networks:
  traefik-public:
    external: true
    driver: overlay
    attachable: true