services:
  speedtest-exporter:
    image: billimek/prometheus-speedtest-exporter:latest
    networks:
      - traefik-public
    ports:
      - "9469:9469"
    deploy:
      placement:
        constraints:
          - node.hostname == rpi4-1 
      replicas: 1

networks:
  traefik-public:
    external: true
    driver: overlay
    attachable: true