{
 "title": "RPI-5 Metrics",
 "time": { "from": "2024-12-04 22:27:06", "to": "now" },
 "panels": [
  { "title": "System Stats", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPI-5 Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_time_seconds - node_boot_time_seconds) / 3600",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Available Storage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{mountpoint=\"/\"} / 1024 / 1024 / 1024",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "System CPU Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Number of Cores",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    { "expr": "max(machine_cpu_cores)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "System Available Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Download Speed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_upload_bits_per_second / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Power Consumption Stats", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Current Power Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tapo_p110_power_consumption_w", "legendFormat": "{{room}}" }
   ]
  },
  {
   "title": "Today Energy Consumption",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tapo_p110_today_energy_wh", "legendFormat": "{{room}}" }
   ]
  },
  {
   "title": "Monthly Energy Consumption",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tapo_p110_month_energy_wh", "legendFormat": "{{room}}" }
   ]
  },
  {
   "title": "Monthly Cost",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (room) (tapo_p110_month_energy_wh * 0.0625) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Daily Run Time Hours",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "tapo_p110_today_runtime_mins{room=\"rpi-poweroutlet\"} / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Containers Stats", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "GBs" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes / 1024 / 1024 / 1024",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total[1m]) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "rate(traefik_service_request_duration_seconds_sum[5m]) / rate(traefik_service_request_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traefik 400/500 Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{code=~\"4.*|5.*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Logs", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Traefik Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "{service_name=`/traefik`} | json | logfmt | drop __error__, __error_details__ |= \"ERR\""
    }
   ]
  }
 ]
}