services:
  server:
    image: codeberg.org/forgejo/forgejo:9
    container_name: forgejo
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.forgejo.rule=Host(`forgejo.home.eduardocouto.dev`)"
    - "traefik.http.routers.forgejo.entrypoints=https"
    - "traefik.http.routers.forgejo.tls=true"
    - "traefik.http.services.forgejo.loadbalancer.server.port=3000"
    - "traefik.http.services.forgejo.loadbalancer.passHostHeader=true"
    - "traefik.docker.network=proxy"

      # HTTP to HTTPS redirect
    - "traefik.http.routers.forgejo-http.rule=Host(`forgejo.home.eduardocouto.dev`)"
    - "traefik.http.routers.forgejo-http.entrypoints=http"
    - "traefik.http.routers.forgejo-http.middlewares=forgejo-https"
    - "traefik.http.middlewares.forgejo-https.redirectscheme.scheme=https"
    environment:
      - USER_UID=1000
      - USER_GID=1000

      - FORGEJO__database__DB_TYPE=postgres
      - FORGEJO__database__HOST=db:5432
      - FORGEJO__database__NAME=forgejo
      - FORGEJO__database__USER=forgejo
      - FORGEJO__database__PASSWD=forgejo
      - ROOT_URL=https://forgejo.home.eduardocouto.dev
    restart: always
    networks:
      - backend
      - proxy
    volumes:
      - ./forgejo:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=forgejo
      - POSTGRES_PASSWORD=forgejo
      - POSTGRES_DB=forgejo
    networks:
      - backend
    volumes:
      - ./postgres:/var/lib/postgresql/data

networks:
  proxy:
    external: true
  backend: