services:
  web:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    hostname: '{{.Node.Hostname}}'
    networks:
      - traefik-public
      - backend
    volumes:
      - data:/data
    env_file:
      - .env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      DATA_DIR: /data
      BROWSER_WEB_URL: http://chrome:9222
    deploy:
      placement:
        constraints:
          - node.hostname == rpi5-1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.hoarder.rule=Host(`hoarder.home.eduardocouto.dev`)"
        - "traefik.http.routers.hoarder.entrypoints=https"
        - "traefik.http.routers.hoarder.tls=true"
        - "traefik.http.services.hoarder.loadbalancer.server.port=3000"
        - "traefik.http.services.hoarder.loadbalancer.passHostHeader=true"
      replicas: 1

  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    hostname: '{{.Node.Hostname}}'
    networks:
      - backend
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    deploy:
      placement:
        constraints:
          - node.hostname == rpi5-1
      replicas: 1

  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    hostname: '{{.Node.Hostname}}'
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    networks:
      - backend
    volumes:
      - meilisearch:/meili_data
    deploy:
      placement:
        constraints:
          - node.hostname == rpi5-1
      replicas: 1

volumes:
  meilisearch:
  data:

networks:
  traefik-public:
    external: true
    driver: overlay
    attachable: true
  backend:
    name: hoarder_backend
    driver: overlay
    attachable: true