services:
  portainer:
    image: portainer/portainer-ce:latest
    hostname: '{{.Node.Hostname}}'
    container_name: portainer
    networks:
      - traefik-public
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      placement:
        constraints:
          - node.hostname == rpi4-1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.portainer.rule=Host(`portainer.home.eduardocouto.dev`)"
        - "traefik.http.routers.portainer.entrypoints=https"
        - "traefik.http.routers.portainer.tls=true"
      replicas: 1

networks:
  traefik-public:
    external: true
    driver: overlay
    attachable: true